SERVER_ERROR =      ({"Message" : "An error occured."},            500)
NOT_FOUND =         ({"Message" : "Resource could not be found."}, 404)
NO_INPUT =          ({"Message" : "No input data provided."},      400)
INVALID_INPUT =     ({"Message" : "Invalid input data."},          422)
ALREADY_EXIST =     ({"Message" : "Resource already exists."},     409)
UNAUTHORIZED =      ({"Message" : "Wrong credentials."},           401)
DOES_NOT_EXIST =    ({"Message" : "Resource does not exists."},    409)
HEADER_NOT_FOUND =  ({"Message" : "Header does not exists."},      999)