GOOD_CREDENTIALS =          ({"Message" : "Good credentials"}, 200)
REGISTRATION_COMPLETE =     ({"Message" : "Registration completed."}, 201)
RESOURCE_ADDED =            ({"Message" : "Resource added."}, 201)
RESOURCE_DELETED =          ({"Message" : "Resource deleted."}, 200)
RESOURCE_UPDATED =          ({"Message" : "Resource updated."}, 200)